# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10HcIEJcM6MF-1eES7kjFdNPo6SCau5Pi
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data=pd.read_excel('/content/petrol.xlsx')
print(data.head())
print(data.dtypes)



x=data.iloc[:,:-1] #iloc: Stands for integer location and is used for integer-location based indexing.
#[:, :-1]: The first colon : before the comma refers to selecting all rows, and :-1 after the comma refers to selecting all columns up to, but not including, the last one.

y=data.iloc[:,3] #: indicates all,3 last column

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

# Remove rows with non-numeric values in the target variable
mask = pd.to_numeric(y, errors='coerce').notna()
x_train = x_train[mask]
y_train = y_train[mask]
y_test=y_test[mask]



print(y_train)
print((x_train))

from  sklearn.linear_model import LinearRegression
regre=LinearRegression()
regre.fit(x_train,y_train)

y_pred=regre.predict(x_test)

from sklearn.metrics import r2_score
score=r2_score(y_pred,y_test)
print(score)

print(y_test)

print(y_pred)
